[0;33m--- Warning: GDB cannot open serial ports accessed as COMx[0m
[0;33m--- Using \\.\COM4 instead...[0m
[0;33m--- esp-idf-monitor 1.7.0 on \\.\COM4 115200[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H[0m
[0m--- 0x4002f44a: [0;33m__riscv_save_2[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpawujj7l_"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpawujj7l_': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpabhq3u9h"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpabhq3u9h': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpyphmkmdp"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpyphmkmdp': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpohviq8ms"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpohviq8ms': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmp8j4d49fe"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmp8j4d49fe': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmp2rd57d7f"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmp2rd57d7f': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpv4yrpyfo"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpv4yrpyfo': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpi6eemvxb"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpi6eemvxb': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpudi5osc2"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpudi5osc2': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpf2zde_uy"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpf2zde_uy': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpy_5t_58b"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpy_5t_58b': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpexhau7wv"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpexhau7wv': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmppu1q_5ue"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmppu1q_5ue': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpe45d0kk9"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpe45d0kk9': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpyatha59m"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpyatha59m': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmp_oxx43or"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmp_oxx43or': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpltas6nty"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpltas6nty': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpaqts8svg"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpaqts8svg': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump detected[0m
[0m--- 0x4080096e: [0;33mpanic_abort[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/panic.c[0m[0m:[1;31m468[0m
[0m--- 0x40807a70: [0;33m__ubsan_include[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/ubsan.c[0m[0m:[1;31m311[0m
[0m--- 0x40800001: [0;33m_vector_table[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/riscv/vectors_intc.S[0m[0m:[1;31m54[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'E:\\workplace\\Choomi\\src\\ChoomiPet\\build\\choomi_pet.elf', '-ex', 'target remote | "D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c6 "C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmptcr56bm8"', '-ex', 'bt']' returned non-zero exit status 1.
--- Warning: b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'D:\\Espressif\\python_env\\idf5.4_py3.12_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c6 C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmptcr56bm8': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0m--- 0x4001975a: [0;33msoftware_reset_cpu[0m[0m in [0;32mROM[0m
[0m--- 0x4200d13e: [0;33mapp_main[0m[0m at [0;32mE:/workplace/Choomi/src/ChoomiPet/main/main.c[0m[0m:[1;31m44[0m
[0m--- 0x40807a65: [0;33m_esp_error_check_failed[0m[0m at [0;32mD:/Espressif/frameworks/esp-idf-v5.4.1/components/esp_system/esp_err.c[0m[0m:[1;31m49[0m
[0;33m--- Stack dump